name: macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    # 修正: make all で全てのセットアップを実行
    - name: Run complete setup
      run: make all

    - name: Check brew installation
      run: |
        which brew
        brew --version
        brew bundle check --file=".bin/darwin/Brewfile" || echo "Some packages may be missing"

    - name: Check symlinks created
      run: |
        ls -la ~/.zshrc ~/.zprofile ~/.gitconfig || echo "Some dotfiles may be missing"

    # cobalt2 テーマ特有のテスト
    - name: Check cobalt2 theme installation
      run: |
        # oh-my-zsh のインストール確認
        if [ -d "$HOME/.oh-my-zsh" ]; then
          echo "✅ oh-my-zsh installed"
        else
          echo "❌ oh-my-zsh not found"
          exit 1
        fi
        
        # テーマファイルの存在確認
        if [ -f "$HOME/.oh-my-zsh/themes/cobalt2.zsh-theme" ]; then
          echo "✅ cobalt2.zsh-theme installed"
        else
          echo "❌ cobalt2.zsh-theme not found"
          exit 1
        fi
        
        # .zshrc のテーマ設定確認
        if grep -q 'ZSH_THEME="cobalt2"' "$HOME/.zshrc"; then
          echo "✅ ZSH_THEME set to cobalt2"
        else
          echo "❌ ZSH_THEME not set to cobalt2"
          exit 1
        fi

    # Powerline インストール確認
    - name: Check Powerline installation
      run: |
        # pip での powerline-status インストール確認
        if python3 -m pip show powerline-status &> /dev/null; then
          echo "✅ powerline-status installed"
        else
          echo "⚠️ powerline-status not found (may be expected in CI)"
        fi
        
        # ローカルの .local/bin にパスが通っているか確認
        if grep -q '.local/bin' "$HOME/.zshrc"; then
          echo "✅ .local/bin added to PATH"
        else
          echo "⚠️ .local/bin not found in PATH"
        fi

    - name: Check if key commands are available
      run: |
        which git && echo "✅ git available"
        which tree && echo "✅ tree available" || echo "⚠️ tree not available"
        which wget && echo "✅ wget available" || echo "⚠️ wget not available"

    # エラーハンドリング改善
    - name: Load .zshrc
      run: |
        echo "=== Debug: Shell environment ==="
        echo "Current shell: $SHELL"
        echo "Available shells:"
        cat /etc/shells || echo "Could not read /etc/shells"
        echo "PATH: $PATH"
        
        echo "=== Debug: ZSH detection ==="
        # 1. command -v の結果を直接確認
        echo "Testing command -v zsh:"
        if command -v zsh >/dev/null 2>&1; then
          echo "✅ command -v zsh succeeded"
          echo "zsh location: $(command -v zsh)"
        else
          echo "❌ command -v zsh failed"
        fi
        
        # 2. which の結果を確認
        echo "Testing which zsh:"
        if which zsh >/dev/null 2>&1; then
          echo "✅ which zsh succeeded"
          echo "zsh location: $(which zsh)"
        else
          echo "❌ which zsh failed"
        fi
        
        # 3. 直接パスで確認
        echo "Testing common zsh paths:"
        ZSH_EXEC=""
        for zsh_path in /bin/zsh /usr/bin/zsh /usr/local/bin/zsh /opt/homebrew/bin/zsh; do
          if [ -x "$zsh_path" ]; then
            echo "✅ Found zsh at: $zsh_path"
            ZSH_EXEC="$zsh_path"
            break
          else
            echo "❌ Not found: $zsh_path"
          fi
        done
        
        if [ -z "$ZSH_EXEC" ]; then
          echo "❌ No working zsh found, cannot proceed"
          exit 1
        fi
        
        echo "=== Debug: .zshrc test ==="
        # ZSH 環境変数を設定
        export ZSH="$HOME/.oh-my-zsh"
        export PATH="$HOME/.local/bin:$PATH"
        
        echo "Content of .zshrc (first 30 lines):"
        head -30 "$HOME/.zshrc" || echo "Could not read .zshrc"
        
        # Step 1: zsh の実行可能性を確認
        echo "Testing zsh execution:"
        if $ZSH_EXEC --version; then
          echo "✅ zsh execution successful"
        else
          echo "❌ zsh execution failed"
          exit 1
        fi
        
        # Step 2: 簡単なコマンドをテスト
        echo "Testing simple zsh command:"
        if $ZSH_EXEC -c "echo 'Hello from zsh'"; then
          echo "✅ Simple zsh command successful"
        else
          echo "❌ Simple zsh command failed"
          exit 1
        fi
        
        # Step 3: 環境変数のテスト
        echo "Testing environment variables in zsh:"
        $ZSH_EXEC -c "echo 'ZSH: $ZSH'; echo 'PATH: $PATH'" || echo "Environment test failed"
        
        # Step 4: .zshrc を読み込んでテスト（verbose）
        echo "Testing .zshrc loading with verbose output:"
        $ZSH_EXEC -c "set -x; source ~/.zshrc && echo 'ZSH configuration loaded successfully'" 2>&1 | tee error.log
        
        exit_code=$?
        echo "Exit code: $exit_code"
        
        # エラーログがある場合の処理
        if [ $exit_code -eq 0 ]; then
          echo "✅ .zshrc loaded without errors"
        else
          echo "❌ .zshrc loading failed with exit code: $exit_code"
          if [ -s error.log ]; then
            echo "Error output:"
            cat error.log
            
            # cobalt2 関連のエラーは警告として扱う
            if grep -q "cobalt2\|powerline" error.log; then
              echo "⚠️ cobalt2/powerline related warnings detected (non-critical in CI)"
            else
              echo "❌ Critical .zshrc loading error"
              exit 1
            fi
          else
            echo "❌ .zshrc loading failed but no error output captured"
            exit 1
          fi
        fi

    - name: Load .zprofile
      run: |
        echo "=== Debug: Shell environment ==="
        echo "Current shell: $SHELL"
        echo "Available shells:"
        cat /etc/shells || echo "Could not read /etc/shells"
        echo "PATH: $PATH"
        
        echo "=== Debug: ZSH detection ==="
        # 1. command -v の結果を直接確認
        echo "Testing command -v zsh:"
        if command -v zsh >/dev/null 2>&1; then
          echo "✅ command -v zsh succeeded"
          echo "zsh location: $(command -v zsh)"
        else
          echo "❌ command -v zsh failed"
        fi
        
        # 2. which の結果を確認
        echo "Testing which zsh:"
        if which zsh >/dev/null 2>&1; then
          echo "✅ which zsh succeeded"
          echo "zsh location: $(which zsh)"
        else
          echo "❌ which zsh failed"
        fi
        
        # 3. 直接パスで確認
        echo "Testing common zsh paths:"
        for zsh_path in /bin/zsh /usr/bin/zsh /usr/local/bin/zsh /opt/homebrew/bin/zsh; do
          if [ -x "$zsh_path" ]; then
            echo "✅ Found zsh at: $zsh_path"
            ZSH_EXEC="$zsh_path"
            break
          else
            echo "❌ Not found: $zsh_path"
          fi
        done
        
        echo "=== Debug: .zprofile test ==="
        if [ -f "$HOME/.zprofile" ]; then
          echo "✅ .zprofile found"
          echo "Content of .zprofile:"
          cat "$HOME/.zprofile" | head -20 || echo "Could not read .zprofile"
          
          if [ -n "$ZSH_EXEC" ]; then
            echo "Using zsh at: $ZSH_EXEC"
            
            # Step 1: zsh の実行可能性を確認
            echo "Testing zsh execution:"
            if $ZSH_EXEC --version; then
              echo "✅ zsh execution successful"
            else
              echo "❌ zsh execution failed"
              exit 1
            fi
            
            # Step 2: 簡単なコマンドをテスト
            echo "Testing simple zsh command:"
            if $ZSH_EXEC -c "echo 'Hello from zsh'"; then
              echo "✅ Simple zsh command successful"
            else
              echo "❌ Simple zsh command failed"
              exit 1
            fi
            
            # Step 3: .zprofile の読み込みをテスト（verbose）
            echo "Testing .zprofile loading with verbose output:"
            $ZSH_EXEC -c "set -x; source ~/.zprofile; echo '.zprofile loaded successfully'" 2>&1 | tee error.log
            
            exit_code=$?
            echo "Exit code: $exit_code"
            
            if [ $exit_code -eq 0 ]; then
              echo "✅ .zprofile loaded without errors"
            else
              echo "❌ .zprofile loading failed with exit code: $exit_code"
              if [ -s error.log ]; then
                echo "Error output:"
                cat error.log
              fi
              # .zprofile の問題は警告として扱う
              echo "⚠️ .zprofile loading failed (non-critical)"
            fi
          else
            echo "⚠️ No working zsh found, skipping .zprofile test"
          fi
        else
          echo "⚠️ .zprofile not found"
        fi

    # 最終的な動作確認
    - name: Final verification
      run: |
        echo "=== Final Environment Check ==="
        echo "Shell: $SHELL"
        echo "ZSH path: $(which zsh 2>/dev/null || echo 'not found')"
        echo "oh-my-zsh: $(ls -la ~/.oh-my-zsh 2>/dev/null | head -1 || echo 'not found')"
        echo "Current theme: $(grep ZSH_THEME ~/.zshrc || echo 'not set')"
        echo "Cobalt2 theme file: $(ls -la ~/.oh-my-zsh/themes/cobalt2.zsh-theme 2>/dev/null || echo 'not found')"
        echo "=== End Check ==="
