name: macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    # 修正: make all で全てのセットアップを実行
    - name: Run complete setup
      run: make all

    - name: Check brew installation
      run: |
        which brew
        brew --version
        brew bundle check --file=".bin/darwin/Brewfile" || echo "Some packages may be missing"

    - name: Check symlinks created
      run: |
        ls -la ~/.zshrc ~/.zprofile ~/.gitconfig || echo "Some dotfiles may be missing"

    # cobalt2 テーマ特有のテスト
    - name: Check cobalt2 theme installation
      run: |
        # oh-my-zsh のインストール確認
        if [ -d "$HOME/.oh-my-zsh" ]; then
          echo "✅ oh-my-zsh installed"
        else
          echo "❌ oh-my-zsh not found"
          exit 1
        fi
        
        # テーマファイルの存在確認
        if [ -f "$HOME/.oh-my-zsh/themes/cobalt2.zsh-theme" ]; then
          echo "✅ cobalt2.zsh-theme installed"
        else
          echo "❌ cobalt2.zsh-theme not found"
          exit 1
        fi
        
        # .zshrc のテーマ設定確認
        if grep -q 'ZSH_THEME="cobalt2"' "$HOME/.zshrc"; then
          echo "✅ ZSH_THEME set to cobalt2"
        else
          echo "❌ ZSH_THEME not set to cobalt2"
          exit 1
        fi

    # Powerline インストール確認
    - name: Check Powerline installation
      run: |
        # pip での powerline-status インストール確認
        if python3 -m pip show powerline-status &> /dev/null; then
          echo "✅ powerline-status installed"
        else
          echo "⚠️ powerline-status not found (may be expected in CI)"
        fi
        
        # ローカルの .local/bin にパスが通っているか確認
        if grep -q '.local/bin' "$HOME/.zshrc"; then
          echo "✅ .local/bin added to PATH"
        else
          echo "⚠️ .local/bin not found in PATH"
        fi

    - name: Check if key commands are available
      run: |
        which git && echo "✅ git available"
        which tree && echo "✅ tree available" || echo "⚠️ tree not available"
        which wget && echo "✅ wget available" || echo "⚠️ wget not available"

    # エラーハンドリング改善
    - name: Load .zshrc
      run: |
        # ZSH 環境変数を設定
        export ZSH="$HOME/.oh-my-zsh"
        export PATH="$HOME/.local/bin:$PATH"
        
        # .zshrc を読み込んでテスト
        zsh -c "source ~/.zshrc && echo 'ZSH configuration loaded successfully'" 2> error.log
        
        # エラーログがある場合の処理
        if [ -s error.log ]; then
          echo "Warning: .zshrc loading produced output:"
          cat error.log
          
          # cobalt2 関連のエラーは警告として扱う
          if grep -q "cobalt2\|powerline" error.log; then
            echo "⚠️ cobalt2/powerline related warnings detected (non-critical in CI)"
          else
            echo "❌ Critical .zshrc loading error"
            exit 1
          fi
        else
          echo "✅ .zshrc loaded without errors"
        fi

    - name: Load .zprofile
      run: |
        if [ -f "$HOME/.zprofile" ]; then
          zsh -c "source ~/.zprofile && echo '.zprofile loaded successfully'" 2> error.log
          if [ -s error.log ]; then
            echo "Warning: .zprofile loading produced output:"
            cat error.log
          else
            echo "✅ .zprofile loaded without errors"
          fi
        else
          echo "⚠️ .zprofile not found"
        fi

    # 最終的な動作確認
    - name: Final verification
      run: |
        echo "=== Final Environment Check ==="
        echo "Shell: $SHELL"
        echo "ZSH installed: $(which zsh)"
        echo "oh-my-zsh: $(ls -la ~/.oh-my-zsh 2>/dev/null | head -1 || echo 'not found')"
        echo "Current theme: $(grep ZSH_THEME ~/.zshrc || echo 'not set')"
        echo "Cobalt2 theme file: $(ls -la ~/.oh-my-zsh/themes/cobalt2.zsh-theme 2>/dev/null || echo 'not found')"
        echo "=== End Check ==="
