name: dotfiles CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  macos-11:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make all

  macos-12:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make all

  macos-latest:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make all